sources = [
    'main.cpp',
    'server.cpp',
    'client.cpp',
    'eid.cpp',
    'netutil.cpp',
]

def configure(conf):
    pass

def build(bld):
    bld.program(
        source=sources,
        target='sydmine',
        lib=['boost_system-mt', 'boost_program_options-mt'],
        defines=['_GLIBCXX_USE_NANOSLEEP'],
        includes=['../third-party/utf8/source'],
        cxxflags='-O3 --std=c++0x --pedantic -Wall -Wfatal-errors -Weffc++')
