def configure(conf):
    pass

def build(bld):
    bld.program(
        source='main.cpp',
        target='sydmine',
        lib=['boost_system-mt'],
        cxxflags='-O3 --std=c++0x --pedantic -Wall -Wfatal-errors -Weffc++')
